/* tslint:disable */
/* eslint-disable */
/**
 * Elastic Email REST API
 * This API is based on the REST API architecture, allowing the user to easily manage their data with this resource-based approach.    Every API call is established on which specific request type (GET, POST, PUT, DELETE) will be used.    To start using this API, you will need your Access Token (available <a href=\"https://elasticemail.com/account#/settings/new/manage-api\">here</a>). Remember to keep it safe. Required access levels are listed in the given request’s description.    This is the documentation for REST API. If you’d like to read our legacy documentation regarding Web API v2 click <a href=\"https://api.elasticemail.com/public/help\">here</a>.
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@elasticemail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { BodyContentType } from './body-content-type';

/**
 * Email body part with user-provided MIME type (text/html, text/plain, etc)
 * @export
 * @interface BodyPart
 */
export interface BodyPart {
    /**
     * Type of the body part
     * @type {BodyContentType}
     * @memberof BodyPart
     */
    ContentType?: BodyContentType;
    /**
     * Actual content of the body part
     * @type {string}
     * @memberof BodyPart
     */
    Content?: string;
    /**
     * Text value of charset encoding for example: iso-8859-1, windows-1251, utf-8, us-ascii, windows-1250 and more…
     * @type {string}
     * @memberof BodyPart
     */
    Charset?: string;
}


