/* tslint:disable */
/* eslint-disable */
/**
 * Elastic Email REST API
 * This API is based on the REST API architecture, allowing the user to easily manage their data with this resource-based approach.    Every API call is established on which specific request type (GET, POST, PUT, DELETE) will be used.    To start using this API, you will need your Access Token (available <a href=\"https://elasticemail.com/account#/settings/new/manage-api\">here</a>). Remember to keep it safe. Required access levels are listed in the given request’s description.    This is the documentation for REST API. If you’d like to read our legacy documentation regarding Web API v2 click <a href=\"https://api.elasticemail.com/public/help\">here</a>.
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@elasticemail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ContactActivity
 */
export interface ContactActivity {
    /**
     * Total emails sent.
     * @type {number}
     * @memberof ContactActivity
     */
    TotalSent?: number;
    /**
     * Total emails opened.
     * @type {number}
     * @memberof ContactActivity
     */
    TotalOpened?: number;
    /**
     * Total emails clicked
     * @type {number}
     * @memberof ContactActivity
     */
    TotalClicked?: number;
    /**
     * Total emails failed.
     * @type {number}
     * @memberof ContactActivity
     */
    TotalFailed?: number;
    /**
     * Last date when an email was sent to this contact
     * @type {string}
     * @memberof ContactActivity
     */
    LastSent?: string | null;
    /**
     * Date this contact last opened an email
     * @type {string}
     * @memberof ContactActivity
     */
    LastOpened?: string | null;
    /**
     * Date this contact last clicked an email
     * @type {string}
     * @memberof ContactActivity
     */
    LastClicked?: string | null;
    /**
     * Last date when an email sent to this contact bounced
     * @type {string}
     * @memberof ContactActivity
     */
    LastFailed?: string | null;
    /**
     * IP from which this contact opened or clicked their email last time
     * @type {string}
     * @memberof ContactActivity
     */
    LastIP?: string;
    /**
     * Last RFC Error code if any occurred
     * @type {number}
     * @memberof ContactActivity
     */
    ErrorCode?: number | null;
    /**
     * Last RFC error message if any occurred
     * @type {string}
     * @memberof ContactActivity
     */
    FriendlyErrorMessage?: string;
}


