/* tslint:disable */
/* eslint-disable */
/**
 * Elastic Email REST API
 * This API is based on the REST API architecture, allowing the user to easily manage their data with this resource-based approach.    Every API call is established on which specific request type (GET, POST, PUT, DELETE) will be used.    The API has a limit of 20 concurrent connections and a hard timeout of 600 seconds per request.    To start using this API, you will need your Access Token (available <a target=\"_blank\" href=\"https://app.elasticemail.com/marketing/settings/new/manage-api\">here</a>). Remember to keep it safe. Required access levels are listed in the given request’s description.    Downloadable library clients can be found in our Github repository <a target=\"_blank\" href=\"https://github.com/ElasticEmail?tab=repositories&q=%22rest+api%22+in%3Areadme\">here</a>
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@elasticemail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CertificateValidationStatus } from './certificate-validation-status';
// May contain unused imports in some cases
// @ts-ignore
import { DomainOwner } from './domain-owner';
// May contain unused imports in some cases
// @ts-ignore
import { TrackingType } from './tracking-type';
// May contain unused imports in some cases
// @ts-ignore
import { TrackingValidationStatus } from './tracking-validation-status';

/**
 * Domain data, with information about domain records.
 * @export
 * @interface DomainData
 */
export interface DomainData {
    /**
     * Domain validation results - when domain has been running through validation process
     * @type {string}
     * @memberof DomainData
     */
    'ValidationLog'?: string;
    /**
     * Name of selected domain.
     * @type {string}
     * @memberof DomainData
     */
    'Domain'?: string;
    /**
     * True, if domain is used as default. Otherwise, false,
     * @type {boolean}
     * @memberof DomainData
     */
    'DefaultDomain'?: boolean;
    /**
     * True, if SPF record is verified
     * @type {boolean}
     * @memberof DomainData
     */
    'Spf'?: boolean;
    /**
     * True, if DKIM record is verified
     * @type {boolean}
     * @memberof DomainData
     */
    'Dkim'?: boolean;
    /**
     * True, if MX record is verified
     * @type {boolean}
     * @memberof DomainData
     */
    'MX'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof DomainData
     */
    'DMARC'?: boolean;
    /**
     * True, if tracking CNAME record is verified
     * @type {boolean}
     * @memberof DomainData
     */
    'IsRewriteDomainValid'?: boolean;
    /**
     * True, if DKIM, SPF, or tracking are still to be verified
     * @type {boolean}
     * @memberof DomainData
     */
    'Verify'?: boolean;
    /**
     * 
     * @type {TrackingType}
     * @memberof DomainData
     */
    'Type'?: TrackingType;
    /**
     * 
     * @type {TrackingValidationStatus}
     * @memberof DomainData
     */
    'TrackingStatus'?: TrackingValidationStatus;
    /**
     * 
     * @type {CertificateValidationStatus}
     * @memberof DomainData
     */
    'CertificateStatus'?: CertificateValidationStatus;
    /**
     * 
     * @type {string}
     * @memberof DomainData
     */
    'CertificateValidationError'?: string;
    /**
     * 
     * @type {TrackingType}
     * @memberof DomainData
     */
    'TrackingTypeUserRequest'?: TrackingType;
    /**
     * 
     * @type {boolean}
     * @memberof DomainData
     */
    'VERP'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof DomainData
     */
    'CustomBouncesDomain'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof DomainData
     */
    'IsCustomBouncesDomainDefault'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof DomainData
     */
    'IsMarkedForDeletion'?: boolean;
    /**
     * 
     * @type {DomainOwner}
     * @memberof DomainData
     */
    'Ownership'?: DomainOwner;
}



