/* tslint:disable */
/* eslint-disable */
/**
 * Elastic Email REST API
 * This API is based on the REST API architecture, allowing the user to easily manage their data with this resource-based approach.    Every API call is established on which specific request type (GET, POST, PUT, DELETE) will be used.    The API has a limit of 20 concurrent connections and a hard timeout of 600 seconds per request.    To start using this API, you will need your Access Token (available <a target=\'_blank\' href=\'https://app.elasticemail.com/marketing/settings/new/manage-api\'>here</a>). Remember to keep it safe. Required access levels are listed in the given request’s description.    Downloadable library clients can be found in our Github repository <a target=\'_blank\' href=\'https://github.com/ElasticEmail?tab=repositories&q=%22rest+api%22+in%3Areadme\'>here</a>
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@elasticemail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CertificateValidationStatus } from './certificate-validation-status';
// May contain unused imports in some cases
// @ts-ignore
import type { DomainOwner } from './domain-owner';
// May contain unused imports in some cases
// @ts-ignore
import type { TrackingType } from './tracking-type';
// May contain unused imports in some cases
// @ts-ignore
import type { TrackingValidationStatus } from './tracking-validation-status';

/**
 * Domain data, with information about domain records.
 */
export interface DomainDetail {
    /**
     * Name of selected domain.
     */
    'Domain'?: string;
    /**
     * True, if domain is used as default. Otherwise, false,
     */
    'DefaultDomain'?: boolean;
    /**
     * True, if SPF record is verified
     */
    'Spf'?: boolean;
    /**
     * True, if DKIM record is verified
     */
    'Dkim'?: boolean;
    /**
     * True, if MX record is verified
     */
    'MX'?: boolean;
    'DMARC'?: boolean;
    /**
     * True, if tracking CNAME record is verified
     */
    'IsRewriteDomainValid'?: boolean;
    /**
     * True, if DKIM, SPF, or tracking are still to be verified
     */
    'Verify'?: boolean;
    'Type'?: TrackingType;
    'TrackingStatus'?: TrackingValidationStatus;
    'CertificateStatus'?: CertificateValidationStatus;
    'CertificateValidationError'?: string;
    'TrackingTypeUserRequest'?: TrackingType;
    'VERP'?: boolean;
    'CustomBouncesDomain'?: string;
    'IsCustomBouncesDomainDefault'?: boolean;
    'IsMarkedForDeletion'?: boolean;
    'Ownership'?: DomainOwner;
}



