/* tslint:disable */
/* eslint-disable */
/**
 * Elastic Email REST API
 * This API is based on the REST API architecture, allowing the user to easily manage their data with this resource-based approach.    Every API call is established on which specific request type (GET, POST, PUT, DELETE) will be used.    To start using this API, you will need your Access Token (available <a href=\"https://elasticemail.com/account#/settings/new/manage-api\">here</a>). Remember to keep it safe. Required access levels are listed in the given request’s description.    This is the documentation for REST API. If you’d like to read our legacy documentation regarding Web API v2 click <a href=\"https://api.elasticemail.com/public/help\">here</a>.
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@elasticemail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { EmailContent } from './email-content';
import { EmailRecipient } from './email-recipient';
import { Options } from './options';

/**
 * Email data
 * @export
 * @interface EmailMessageData
 */
export interface EmailMessageData {
    /**
     * List of recipients (visible to others)
     * @type {Array<EmailRecipient>}
     * @memberof EmailMessageData
     */
    Recipients?: Array<EmailRecipient>;
    /**
     * Proper e-mail content
     * @type {EmailContent}
     * @memberof EmailMessageData
     */
    Content?: EmailContent;
    /**
     * E-mail configuration
     * @type {Options}
     * @memberof EmailMessageData
     */
    Options?: Options;
}


