/* tslint:disable */
/* eslint-disable */
/**
 * Elastic Email REST API
 * This API is based on the REST API architecture, allowing the user to easily manage their data with this resource-based approach.    Every API call is established on which specific request type (GET, POST, PUT, DELETE) will be used.    The API has a limit of 20 concurrent connections and a hard timeout of 600 seconds per request.    To start using this API, you will need your Access Token (available <a target=\'_blank\' href=\'https://app.elasticemail.com/marketing/settings/new/manage-api\'>here</a>). Remember to keep it safe. Required access levels are listed in the given request’s description.    Downloadable library clients can be found in our Github repository <a target=\'_blank\' href=\'https://github.com/ElasticEmail?tab=repositories&q=%22rest+api%22+in%3Areadme\'>here</a>
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@elasticemail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EventType } from './event-type';
// May contain unused imports in some cases
// @ts-ignore
import type { MessageCategory } from './message-category';

/**
 * Detailed information about message recipient
 */
export interface RecipientEvent {
    /**
     * ID number of transaction
     */
    'TransactionID'?: string;
    /**
     * ID number of selected message.
     */
    'MsgID'?: string;
    /**
     * Default From: email address.
     */
    'FromEmail'?: string;
    /**
     * Ending date for search in YYYY-MM-DDThh:mm:ss format.
     */
    'To'?: string;
    /**
     * Default subject of email.
     */
    'Subject'?: string;
    'EventType'?: EventType;
    /**
     * Creation date
     */
    'EventDate'?: string;
    /**
     * Name of selected channel.
     */
    'ChannelName'?: string;
    'MessageCategory'?: MessageCategory;
    /**
     * Date of next try
     */
    'NextTryOn'?: string | null;
    /**
     * Error message if sending has failed (FailedAttempt or Bounce)
     */
    'Message'?: string;
    /**
     * IP which this email was sent through
     */
    'IPAddress'?: string;
    /**
     * Name of an IP pool this email was sent through
     */
    'PoolName'?: string;
}



