/* tslint:disable */
/* eslint-disable */
/**
 * Elastic Email REST API
 * This API is based on the REST API architecture, allowing the user to easily manage their data with this resource-based approach.    Every API call is established on which specific request type (GET, POST, PUT, DELETE) will be used.    To start using this API, you will need your Access Token (available <a href=\"https://elasticemail.com/account#/settings/new/manage-api\">here</a>). Remember to keep it safe. Required access levels are listed in the given request’s description.    This is the documentation for REST API. If you’d like to read our legacy documentation regarding Web API v2 click <a href=\"https://api.elasticemail.com/public/help\">here</a>.
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@elasticemail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { BodyPart } from './body-part';
import { TemplateScopeType } from './template-scope-type';

/**
 * New template object
 * @export
 * @interface TemplatePayload
 */
export interface TemplatePayload {
    /**
     * Template name
     * @type {string}
     * @memberof TemplatePayload
     */
    Name?: string;
    /**
     * Default subject of email.
     * @type {string}
     * @memberof TemplatePayload
     */
    Subject?: string;
    /**
     * Email content of this template
     * @type {Array<BodyPart>}
     * @memberof TemplatePayload
     */
    Body?: Array<BodyPart>;
    /**
     * Visibility of a template
     * @type {TemplateScopeType}
     * @memberof TemplatePayload
     */
    TemplateScope?: TemplateScopeType;
}


